spring.application.name=springboot-layered-architecture
server.port=8083

# Database or Datasource configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=david
spring.datasource.password=1234
spring.datasource.url=jdbc:postgresql://localhost:1300/sb14_db

# JPA configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true